<?php

namespace AppBundle\Repository;

/**
 * ClimbingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClimbingRepository extends \Doctrine\ORM\EntityRepository
{
}
