<?php

namespace AppBundle\Repository;

/**
 * NationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NationRepository extends \Doctrine\ORM\EntityRepository
{
}
